### ISSUE TITLE
대문자 확장자 업로드 불가

### ISSUE THREAD

**Issue by simkyuwon** [inerplat/JoyurIZ-WEB#2]
확장자가 대문자로된 파일 업로드시 인식 불가
확장자를 소문자로 변경시 정상적으로 작동함

**Comment by inerplat** [comment]
https://github.com/inerplat/JoyurIZ-WEB/blob/253620ec8bab5e40d4435ac95778dc13212d35e0/server/server.js#L70-L72

로컬 테스트를 윈도우에서 하고 배포를 리눅스에서 하니 발생한 문제
